// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Migrate/CLI commands need a direct (non-pooled) connection; the app's
  // runtime queries go through DATABASE_URL (pooled) via the adapter in
  // src/lib/prisma.ts instead.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
